### ISSUE TITLE
Pods should be installed

### ISSUE THREAD

**Issue by kenmhaggerty** [learn-co-curriculum/objc-holiday-properties#2]
I had to run `pod install` after forking this repo in order to get it to build. I'm guessing that this should probably be done for the student ahead of time, as the lab instructions do not specify this.

**Comment by markedwardmurray** [comment]
New versions of Specta & Expecta have been released since this lab was last updated, probably for Xcode 7.2 compatibility. Just need somebody to push up the new versions to the canonical.

**Comment by susanlovaglio** [comment]
Updated the files, thanks for raising this issue!
