### ISSUE TITLE
Build fails with following error

### ISSUE THREAD

**Issue by richardsonjm** [learn-co-curriculum/objc-holiday-properties#3]
Please see error message below. 

pod --version 0.37.2
Xcode Version 7.3 (7D175)

```
CompileStoryboard objc-holiday-properties/Main.storyboard
    cd /Users/johnrichardson/Development/code/learn/objc/objects/objc-holiday-properties-001
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module objc_holiday_properties --output-partial-info-plist /Users/johnrichardson/Library/Developer/Xcode/DerivedData/objc-holiday-properties-ekxnvghimvqnlrgvynfhpynkmdid/Build/Intermediates/objc-holiday-properties.build/Debug-iphonesimulator/objc-holiday-properties.build/Main-SBPartialInfo.plist --auto-activate-custom-fonts --target-device iphone --minimum-deployment-target 8.0 --output-format human-readable-text --compilation-directory /Users/johnrichardson/Development/code/learn/objc/objects/objc-holiday-properties-001/objc-holiday-properties/Main.storyboard

/* com.apple.ibtool.errors */
: error: Not enough arguments provided; where is the input document to operate on?
```

**Comment by richardsonjm** [comment]
Looks like my fork was for objc-holiday-properties-001, not this repo. Sorry for the confustion

**Comment by markedwardmurray** [comment]
hm, weird. looks like a clang error. try cleaning your derived data and see if that resolves it

You did raise an issue on the correct repository. This is the curriculum "template" that gets distributed to each of the "batches" on `learn-co-students`.

**Comment by richardsonjm** [comment]
Ok. Didn't realize the change in name from curriculum to students. It looks like this repo on [learn-co-students](https://github.com/learn-co-students/objc-holiday-properties-001) is several commits behind the master on [learn-co-curriculum](https://github.com/learn-co-curriculum/objc-holiday-properties).

**Comment by markedwardmurray** [comment]
hm @spencer1248 (hi dude!) , looks like the deployment to 001 didn't get updated correctly a while back. Is it that batch still being supported? John, you should probably reopen this issue, i think it's legit.
